version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes:
      - ./mongo-logs:/var/log/mongodb/
      - ./data:/var/lib/mongodb
    ports:
      - "27017:27017"
    #command: mongod --config /etc/mongod.conf
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongo
